version: '3.8'

services:
  # Service Database (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: weshare_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=weshare123
      - POSTGRES_DB=weShareDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # Service
  pgadmin:
    image: dpage/pgadmin4
    container_name: weshare_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@weshare.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: